projects:
  paycodegql:
    schemaPath: amplify/backend/api/paycodegql/build/schema.graphql
    includes:
      - ../../packages/graphql/src/**/*.ts
    excludes:
      - amplify/**
      - ../../packages/graphql/src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ../../packages/graphql/src/API.ts
        docsFilePath: ../../packages/graphql/src
        region: us-west-2
        maxDepth: 3
extensions:
  amplify:
    version: 3
