apis:
  paycode-proxy-api:
    root:  'openapi.spec.yaml'
  paycode-bundled:
    root: 'openapi.bundled.yaml'
extends:
  - recommended
rules:
  no-unused-components: error
  no-empty-servers: off

# Documentation Reference for recommended
#  Errors:

#     no-empty-servers
#     no-enum-type-mismatch
#     no-example-value-and-externalValue
#     no-identical-paths
#     no-path-trailing-slash
#     no-server-trailing-slash
#     no-server-variables-empty-enum
#     no-undefined-server-variable
#     no-unresolved-refs
#     operation-operationId-unique
#     operation-operationId-url-safe
#     operation-parameters-unique
#     operation-summary
#     path-declaration-must-exist
#     path-not-include-query
#     path-parameters-defined
#     security-defined
#     spec-components-invalid-map-name
#     spec

# Warnings:

#     configurable rules
#     info-license-url
#     info-license
#     no-ambiguous-paths
#     no-invalid-media-type-examples
#     no-server-example-com
#     no-unused-components
#     operation-2xx-response
#     operation-4xx-response
#     operation-operationId
#     tag-description